%% Just a little calc...

% vert at pi phase
vertBranch3Stab = pickAndSwitch(funcs, ...
    branch_stst, ...
    param.feed_ampli.index, ...
    300, ...
    param, ...
    'reverse',1, ...
    'nunst_color', nunst_branch_stst, ...
    'point', 2076);

plot_branch(vertBranch3Stab, param, ...
    'nunst_color', vertBranch3Stab.nunst)

save([master_options.datadir_specific,'vertBranch3Stab.mat'], ...
    'vertBranch3Stab');


%% Hopf conts from top of vert

hopfs_vrtBrn3 = bifurFoldHopfMultiCreator( ...
    funcs, ...
    vertBranch3Stab, ...
    param, ...
    vertBranch3Stab.indHopf, ...
    250);

branchplot = figure;

for i = 1:numel(hopfs_vrtBrn3)
    % Add each hopf
    if isa(hopfs_vrtBrn3(i).error,'double') && hopfs_vrtBrn3(i).error == 0
        plot_branch(hopfs_vrtBrn3(i), param, ...
            'add_2_gcf', 1, 'color','c');
    end
end

save([master_options.datadir_specific,'hopfs_vrtBrn3.mat'], ...
    'hopfs_vrtBrn3');

%% horiz at 0.5, stable
horizBranch05Stab = pickAndSwitch(funcs, ...
    vertBranch3Stab, ...
    param.feed_phase.index, ...
    350, ...
    param, ...
    'axes_indParam', [param.feed_phase.index, param.feed_ampli.index], ...
    'reverse',1, ...
    'nunst_color', vertBranch3Stab.nunst, ...
    'point', 172);

plot_branch(horizBranch05Stab, param, ...
    'nunst_color', horizBranch05Stab.nunst)

save([master_options.datadir_specific,'horizBranch05Stab.mat'], ...
    'horizBranch05Stab');


%% unstab
horizBranch05unstab = pickAndSwitch(funcs, ...
    vertBranch3Stab, ...
    param.feed_phase.index, ...
    350, ...
    param, ...
    'axes_indParam', [param.feed_phase.index, param.feed_ampli.index], ...
    'reverse',1, ...
    'nunst_color', vertBranch3Stab.nunst, ...
    'point', 338);

plot_branch(horizBranch05unstab, param, ...
    'nunst_color', horizBranch05unstab.nunst)

save([master_options.datadir_specific,'horizBranch05unstab.mat'], ...
    'horizBranch05unstab');


%% Plot @ 560 microamps, branches

branchplot = figure;

% Plot each hopf_branch
namesHopfBranches = fieldnames(hopf_branches);
for i = [12,13,14,15,16,17] % 1:numel(namesHopfBranches)
    % Add each hopf_branch
    if ~any(strcmp('error', ... 
            fieldnames(hopf_branches.(namesHopfBranches{i}))))
        % Only plot hopf_branches that DO NOT have errors
        plot_branch(hopf_branches.(namesHopfBranches{i}), param, ...
            'add_2_gcf', 1, 'color','c');
    end
end


% Plot each fold_branch

namesFoldBranches = fieldnames(fold_branches);

for i = [7,8] % 1:numel(namesFoldBranches)
    % Add each hopf_branch
    if ~any(strcmp('error',...
            fieldnames(fold_branches.(namesFoldBranches{i}))))
        % Only plot fold_branches that DO NOT have errors
        plot_branch(fold_branches.(namesFoldBranches{i}), param, ...
            'add_2_gcf', 1, 'color','r');
    end
    
end

%% Omega plot

[~, omegaplot] = plot_branch(branch_stst,param, ...
    'nunst_color',nunst_branch_stst);