function [ f ] = qd1EfAlphaNonDimSelfRot(...
    E, Etau, rho, rhotau, n, ntau, ...
    kappa_s, kappa_w, mu_s, mu_w, epsi_ss, epsi_ww, epsi_sw, epsi_ws, ...
    beta, J_p, eta, ...
    tau_r, S_in, V, Z_QD, n_bg, ...
    tau_sp, T_2, A, hbar_omega, epsi_tilda, J, ...
    feed_phase, feed_ampli, tau_fb, ...
    epsi0, hbar, e0, c0, ...
    alpha_par, omega )
% UNFINISHED NOT WORKING
%
%Nondimensionalized version of a single electric field, coherent feedback,
%phase-amplitude coupled system. This function is 'human accessible' and
%gets processed later on in the program. Additionally, the rotation has
%already been included. Check qd_1ef_phaseAmp_nondim for the first system.
%   Input:
%
%   Output:
%

A_rot=[0,-1,0,0; 1,0,0,0; 0,0,0,0; 0,0,0,0];
expA_rot=@(phi) [cos(phi),-sin(phi),0,0; ...
    sin(phi),cos(phi),0,0; ...
    0,0,1,0; ...
    0,0,0,1];

xx = qd_1ef_phaseAmp_nondim(E, Etau, rho, rhotau, n, ntau, ...
    kappa_s, kappa_w, mu_s, mu_w, epsi_ss, epsi_ww, epsi_sw, epsi_ws, ...
    beta, J_p, eta, ...
    tau_r, S_in, V, Z_QD, n_bg, ...
    tau_sp, T_2, A, hbar_omega, epsi_tilda, J, ...
    feed_phase, feed_ampli, tau_fb, ...
    epsi0, hbar, e0, c0, ...
    alpha_par );

xxrot = xx

end

