function [ f ] = qd_sameEF_ROT(...
    E1, Etau1, E2, Etau2, rho, rhotau, n, ntau, ...
    kappa_s, kappa_w, mu_s, mu_w, epsi_ss, epsi_ww, epsi_sw, epsi_ws, ...
    beta, J_p, eta, ...
    tau_r, S_in, V, Z_QD, n_bg, ...
    tau_sp, T_2, A, hbar_omega, epsi_tilda, J, ...
    feed_phase, feed_ampli, tau_fb, ...
    epsi0, hbar, e0, c0, ...
    alpha_par )
%Produces two identical electric fields. Otherwise, it's like
%qe_1ef_phase_Amp_nondim.
%
%The second electric field is literally ignored in the system.


epsi_bg = n_bg^2;

lambda = tau_sp;
theta = sqrt((epsi_ss*epsi_tilda)^-1);
phi = (S_in*tau_sp)^(-1);


g = ((norm(mu_s)^2)*T_2/(2*hbar^2))*(1+(E1.*conj(E1))).^(-1);

Edot1 = lambda*( ... 
    (1 - 1.0i*alpha_par) ...
    *( ...
    (hbar_omega/(epsi0*epsi_bg))*(2*Z_QD/V)*g.*(2*rho-1).*E1 ...
    - kappa_s*E1 ...
    ) ...
    + kappa_s*feed_ampli*exp(-1.0i*feed_phase)*Etau1 ...
    + ( ...
    (1/norm(theta)^2)*(beta*hbar_omega/(epsi0*epsi_bg)) ... 
    *(2*Z_QD/V)*(rho/tau_sp).*(E1./(E1.*conj(E1))) ...
    ) ... 
    );

Edot2 = lambda*( ... 
    (1 - 1.0i*alpha_par) ...
    *( ...
    (hbar_omega/(epsi0*epsi_bg))*(2*Z_QD/V)*g.*(2*rho-1).*E2 ...
    - kappa_s*E2 ...
    ) ...
    + kappa_s*feed_ampli*exp(-1.0i*feed_phase)*Etau2 ...
    + ( ...
    (1/norm(theta)^2)*(beta*hbar_omega/(epsi0*epsi_bg)) ... 
    *(2*Z_QD/V)*(rho/tau_sp).*(E2./(E2.*conj(E2))) ...
    ) ... 
    );

rhodot = lambda*( ...
    -(norm(theta)^2*g.*(2*rho-1).*(E1.*conj(E1))) ...
    - (rho/tau_sp) + (phi*S_in*n.*(1-rho)) ... 
    ); 

ndot = (lambda/phi)*( ...
    ((eta/(e0*A))*(J-J_p)) ...
    - phi*((S_in*n).*((2*Z_QD/A)*(1-rho))) - phi*(n/tau_r) ...
    );

f = cat(1,real(Edot1),imag(Edot1),real(Edot2),imag(Edot2),rhodot,ndot);

end

